BSidesBadgeServer/BSidesBadgeServer/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
#from badge import views

from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^badge/', include('badge.urls',namespace="badge")),
    url(r'^', include('dashboard.urls',namespace="dashboard")),
    #url(r'^',badgeDashboard.as_view(),name='dashboard'),
    #url(r'dashboard/$',badgeDashboard.as_view(),name='dashboard'),

    
]

BSidesBadgeServer/badge/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
#from badge import views
from badge.views import badgeCheckin,badgeGetHash, badgeAddAlias, badgeAddChallenge, getBadgeDetails, getAllBadges, saveCurrentTeamStandings, RPSSL_api, aboutPage, FAQ, theGame

from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    url(r'checkin/(?P<badgeID>[A-Za-z0-9]+)/$', csrf_exempt(badgeCheckin.as_view()), name='checkin'),
    url(r'gethash/(?P<badgeID>[A-Za-z0-9]+)/$', csrf_exempt(badgeGetHash.as_view()), name='gethash'),
    url(r'addalias/$', badgeAddAlias.as_view(), name='addalias'),
    url(r'addhash/$', badgeAddChallenge.as_view(), name='addhash'),
    url(r'badgeDetails/(?P<badgeID>[A-Za-z0-9]+)/$', getBadgeDetails.as_view(), name='badgeDetails'),
    url(r'RPSSL/(?P<challengerBadge>[A-Za-z0-9]+)/(?P<selection>[0-9]+)/(?P<badgeID>[A-Za-z0-9]+)/$', csrf_exempt(RPSSL_api.as_view()), name='badgeDetails'),
    url(r'listBadges/$', getAllBadges.as_view(), name='badgeDetails'),
    url(r'saveGameState/$', saveCurrentTeamStandings.as_view(), name='saveCurrentTeamStandings'),
    url(r'thegame/$', theGame.as_view(), name='thegame'),
    url(r'faq/$', FAQ.as_view(), name='faq'),
    url(r'about/$', aboutPage.as_view(), name='about'),
    #url(r'workbench/(?P<badgeID>[0-9]+)$', badgeGetHash.as_view(), name='workbench'),
    
]

BSidesBadgeServer/challenges/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
#from badge import views
from challenges.views import challengeDashboard, challengeAjax

from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    #url(r'ajax/$', csrf_exempt(challengeAjax.as_view()), name='ajax'),
    url(r'^', views.challengeDashboard.as_view(), name='dashboard'),
    
]

BSidesBadgeServer/dashboard/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
#from badge import views
from .views import badgeDashboard, badgeDashboardAjax
from . import views
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    url(r'ajax/$', csrf_exempt(badgeDashboardAjax.as_view()), name='ajax'),
    url(r'^', views.badgeDashboard.as_view(), name='dashboard'),
    
    
]

BSidesBadgeServer/challenges/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

BSidesBadgeServer/challenges/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.views.generic import TemplateView
from django.http import HttpResponse, JsonResponse
from badge.models import Challenges

class challengeDashboard(TemplateView):
    template_name = "challengeList.html"
    def get(self, request, *args, **kwargs):
        return JsonResponse({});

class badgeDashboardAjax(TemplateView):
    template_name = "index.html"
    def get(self, request, *args, **kwargs):
        return JsonResponse({});
    

BSidesBadgeServer/templates/aboutPage.html
{% extends "base.html" %} {% block content %}
    

{% load staticfiles %}
<!--<link rel="stylesheet" href="{% static 'chosen_v1.6.2/chosen.css' %}">--> 
<script src="{% static 'Highcharts/code/highcharts.js' %}"></script>
<script src="{% static 'Highcharts/code/modules/exporting.js' %}"></script>


<h4>About the Badges</h4><hr/>
<div style="text-align: left">
  <div class="alert alert-dismissible alert-info">All three badges presented at BSides Cape Town 2016</div>
  <a href="{% static 'images/allthreebadges.jpg' %}" target="_blank">
	<img alt="All three badges" height="300px" src="{% static 'images/allthreebadges.jpg' %}"/>
  </a><br/>
  From left to right, White ( Attendee ), Blue (Speaker/presenter/organiser), Black (Badge Staff)
</div>
<br/>
<h4>Badge Interface</h4><hr/>
<div style="text-align: left; ">
  <div class="alert alert-dismissible alert-info">Badge Interface</div>
  <a href="{% static 'images/onebadge_label.jpg' %}" target="_blank">
	<img alt="Labelled Badge" height="300px" src="{% static 'images/onebadge_label.jpg' %}"/>
  </a><br/>
  
  The badge has the following components
  <ul>
	<li>Buttons</li>
	<li>Screen</li>
	<li>Infrared Receiver and Transmitter</li>
	<li>ESP8266 (processor and WiFi)</li>
	<li>600mah Lipo Battery</li>
	<li>USB Charging</li>
  </ul>

</div>
<br/>
<h4>Badge Screens</h4><hr/>
<div style="text-align: left; ">
  <div class="alert alert-dismissible alert-info">Different Screens on the badges</div>
  <a href="{% static 'images/bsidesLogoScreen.jpg' %}" target="_blank">
	<img alt="Logo Screen" width="100px" src="{% static 'images/bsidesLogoScreen.jpg' %}"/>
  </a>
  
  <a href="{% static 'images/BadgeScreen.jpg' %}" target="_blank">
	<img alt="Badge Info Screen" width="100px" src="{% static 'images/BadgeScreen.jpg' %}"/>
  </a>
  
  <a href="{% static 'images/ChallengesScreen.jpg' %}" target="_blank">
	<img alt="Challenges Screen" width="100px" src="{% static 'images/ChallengesScreen.jpg' %}"/>
  </a>
  
  <a href="{% static 'images/RPSSL.jpg' %}" target="_blank">
	<img alt="Rock Paper Scissors Spock Lizard" width="100px" src="{% static 'images/RPSSL.jpg' %}"/>
  </a>
  
  <a href="{% static 'images/Schedule.jpg' %}" target="_blank">
	<img alt="Schedule Screen" width="100px" src="{% static 'images/Schedule.jpg' %}"/>
  </a>
  <br/><br/>
  The badges themselves offer 5 different screens that are available listed below as well as playing <a href="{% url 'badge:thegame' %}">The Game</a>. Below lists what each badge has.
  <br/><br/><h4>Logo Screen</h4><hr/>
  <a href="{% static 'images/bsidesLogoScreen.jpg' %}" target="_blank">
	<img alt="Logo Screen" width="350px" src="{% static 'images/bsidesLogoScreen.jpg' %}"/>
  </a><br/><br/>
  This screen simply shows the BSides Cape Town 2016 display.
  
  <br/><br/><h4>Badge/About Screen</h4><hr/>
  <a href="{% static 'images/BadgeScreen.jpg' %}" target="_blank">
	<img alt="Badge Info Screen" width="350px" src="{% static 'images/BadgeScreen.jpg' %}"/>
  </a><br/>
  This screen lists the details about your badge, including the following:<br/><br/>
  * Number of <a href="{% url 'badge:addhash' %}">challenges</a> solved.<br/>
  * The code used to <a href="{% url 'badge:addalias' %}">change the alias</a><br/>
  * The Badge ID also used on the alias page<br/>
  
  
  <br/><br/><h4>Challenge Screen</h4><hr/>
  <a href="{% static 'images/ChallengesScreen.jpg' %}" target="_blank">
	<img alt="Challenges Screen" width="350px" src="{% static 'images/ChallengesScreen.jpg' %}"/>
  </a><br/><br/>
  This screen lists the challenges that you have completed as well as give you a chance to "play" the prize if available.
  <br/><br/>
  To use this screen use the keypad on the right (A,B,C,D buttons) to move left and right (A and D) and when you wish to play the 'prize' you can press up (B). <br/>
  The prizes could be one of the following:<br/><br/>
  * Warbadging (scan available WiFi networks)<br/>
  * Pong ( 2 players on one badge )<br/>
  * Skeleton Dance <br/>
  * Alias Waterfall <br/><br/>
  <div class="alert alert-dismissible alert-danger">
	TO QUIT CHALLENGES PLEASE PRESS TO TWO INNER BUTTONS ( LEFT and A)
  </div>
  <br/><br/><h4>Rock, Paper, Scissors, Spock, Lizard</h4><hr/>
  <a href="{% static 'images/RPSSL.jpg' %}" target="_blank">
	<img alt="Rock Paper Scissors Spock Lizard" width="350px" src="{% static 'images/RPSSL.jpg' %}"/>
  </a><br/><br/>
  This screen is the Rock, Paper, Scissors, Spock, Lizard. To find out about this game you can <a href='https://en.wikipedia.org/wiki/Rock%E2%80%93paper%E2%80%93scissors#Additional_weapons' target='_blank'>click here</a>.
  <br/><br/>
  To play this game do the following:<br/>
  1. Make your selection using the A and D keys between Rock, Paper, Scissors, Spock, Lizard<br/>
  2. Press the B to start searching for players<br/>
  3. Put your badge near another badge that is also searching for players<br/>
  4. When your selection list shows additional badges use the B and C keys to select your opponent ( Note this will be the opponents Badge ID)<br/>
  5. Win or Lose!<br/><br/><br/>
  
  <div class="alert alert-dismissible alert-danger">
	TO QUIT THIS GAME PLEASE PRESS TO TWO INNER BUTTONS ( LEFT and A)
  </div>
  
  
  <br/><h4>Schedule</h4><hr/>
  <a href="{% static 'images/Schedule.jpg' %}" target="_blank">
	<img alt="Schedule Screen" width="350px" src="{% static 'images/Schedule.jpg' %}"/>
  </a><br/>
  The Schedule screen shows.... the schedule.<br/>
  To navigate this screen use the A and D keys.
  <br/><br/>
  <br/><h4>About Page</h4><hr/>
  This page shows the current build and git commit status.
</div>



{% endblock %}

BSidesBadgeServer/templates/addChallenge.html
{% extends "base.html" %} {% block content %}
    
{% load bootstrap %}
{% load staticfiles %}

<h3>Submit Challenge Token</h3><hr/>
<div class="alert alert-dismissible alert-info">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Heyo!</strong> Please type in your badge number and challenge token. If correct your badge will update when it next syncs.
</div>

<form action="" method="post" class="">
    {{ form|bootstrap }}
     <div class="actions row">
         <p class="col-md-3 col-sm-5 submit">
             <input type="submit" value="Submit Challenge Token!" name="_update" class="btn btn-primary" />
         </p>
         
         {% csrf_token %}
     </div>
 </form>

<h3>Challenges</h3><hr/>
Challenges unlock <a href='#prizes'>various things</a> on the badge, it might be an animation or a particular application that you can run on the badge. To unlock a challenge simply put in your challenge code as well as your badge ID. You can view the challenges below<br/> <br/>

<div class="alert alert-dismissible alert-success">
  <strong>Alias</strong>
</div>
<div>
  To unlock this simply set the alias for your badge!
</div>
<div><strong>Unlocks:</strong> Alias Rainfall</div><br/><br/>

<div class="alert alert-dismissible alert-success">
  <strong>RetroRom</strong>
</div>
<div>
  To access this challenge browse to <a href='http://hypn.za.net/bsides/retroport.php'>http://hypn.za.net/bsides/retrorom.php</a>
</div>
<div><strong>Unlocks:</strong> Pong</div><br/><br/>


<div class="alert alert-dismissible alert-success">
  <strong>RetroPort</strong>
</div>
<div>
  To access this challenge browse to <a href='http://hypn.za.net/bsides/retroport.php'>http://hypn.za.net/bsides/retroport.php</a>
</div>
<div><strong>Unlocks:</strong> Alias Rainfall</div><br/><br/>

<div class="alert alert-dismissible alert-success">
  <strong>HappyCorp</strong>
</div>
<div>
Hello Eli

Before recieving your prize, you must prove that you are worthy.

The first step is to find a webpage which has been cleverly hidden below:</div>
<div><strong>Unlocks:</strong> Skeleton</div><br/><br/>

<div class="alert alert-dismissible alert-success">
  <strong>Secret Squirrel</strong>
</div>
<div>
The BSides lunch tokens seemed to have had some very clever imagary hidden within them. Perhaps that could be a clue to this challenge</div>
<div><strong>Unlocks:</strong> Warbadging</div><br/><br/>

<a name="challenges"><h3>Challenge Applications</h3><hr/></a>
<div class="alert alert-dismissible alert-info">
<strong>PONG</strong>
</div>
The Pong application lets you play pong against another player by holding the badge with the screen between you and the other person!
<br/><br/>
First person to five wins.
<br/><br/>
To <strong>QUIT</strong> the game press the two buttons closer to the screen (right and A)

<br/><br/>


<div class="alert alert-dismissible alert-info">
<strong>WARBADGING</strong>
</div>
Warbadging is where you can use the badge to scan for Wireless networks. It will scan up to 30 networks and allow you to scroll through them. It will show you the signal strength, what encryption the network is running ( WPA = WP, WPA2 = W2, OPEN = OP, AUTO = AU, Unknown = ??).
You can use this to take with you to find wireless networks. It will also scan all the channels!
<br/><br/>

To <strong>QUIT</strong> this press the two buttons closer to the screen (right and A)<br/><br/>


<div class="alert alert-dismissible alert-info">
<strong>Skeleton!</strong>
</div>
Get an adorable 8 bit skeleton to run across your screen<br/><br/>

<div class="alert alert-dismissible alert-info">
<strong>Alias Rainfall</strong>
</div>
Have your alias rain down from the top to the bottom of the screen.


<h3 style='color: #f00'>This stuff will be removed for actual release</h3>
<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <td><strong>Challenge Name</strong></td>
    <td><strong>Challenge Description</strong></td>
    <td><strong>Challenge Password</strong></td>
    <td><strong>Challenge Valid Code</strong></td>
  </tr>
  </thead>
{% for c in Challenges %}
<tr>
  <td>{{c.challenge_name}}</td>
  <td>{{c.challenge_description}}</td>
  <td>{{c.challenge_pass}}</td>
  <td>{{c.challenge_valid}}</td>
</tr>
{% endfor %}
</table>

<h4>Encrypt</h4>
This will give the valid output for *all* challenges<br/><br/>
<strong>Badge Number</strong><input type="text" name="bnumber" id='bnumber'/><br/><br/>
<a href="#" class="btn btn-default" onclick='getCrypts();return false;'>Show Values</a><br/>
<div id='results'>&nbsp;</div>



<h3>Encryption</h3>
<XMP>
  Badge encryption works as follows:
  
  Encrypt:
  --------
  Take badge number and add to secret key from challenge
  Use this as encryption key ( padded with leading 0s to 32 characters)
  AES Encrypt in CBC mode with a 16 char IV
  Add IV to front of encryption and B64 encode entire thing
  
  Decrypt:
  --------
  Take badge number and add to secret key from challenge
  Use this as encryption key ( padded with leading 0s to 32 characters)
  Base64 decode submitted hash
  Take first 16 chars of this as IV
  AES Decrypt in CBC mode with these 16 as IV
  If outputted string matches the challenges 'valid code' then we add it to badge!
  
</XMP>
<h3>Python Code for Encryption/Decryption</h3>
<XMP>
BS = 16
pad = lambda s: s + (BS - len(s) % BS) * chr(BS - len(s) % BS) 
unpad = lambda s : s[:-ord(s[len(s)-1:])]

class AESCipher:
	def __init__( self, key ):
		#key = base64.b64encode(key)
		if(len(key) > 32):
			key = key[:32]
		else:
			key = key.zfill(32)
		
		self.key = key

	
	
	def encrypt( self, raw ):
		raw = pad(raw)
		iv = Random.new().read( AES.block_size )
		cipher = AES.new( self.key, AES.MODE_CBC, iv )
		return base64.b64encode( iv + cipher.encrypt( raw ) ) 
	
	def decrypt( self, enc ):
		enc = base64.b64decode(enc)
		iv = enc[:16]
		cipher = AES.new(self.key, AES.MODE_CBC, iv )
		return unpad(cipher.decrypt( enc[16:] ))

</XMP>


<script type="text/javascript">
  function getCrypts() {
    //code
  
   $.ajax({
    'url' : '{% url 'badge:addhash' %}',
  //The type of request, also known as the "method" in HTML forms
  //Can be 'GET' or 'POST'
    'type' : 'GET',
  //Any post-data/get-data parameters
  //This is optional
    'data' : {
      'badgeNum' : $('#bnumber').val(),
      
    },
  //The response from the server
    'success' : function(data) {
    //You can use any jQuery/JavaScript here!!!
    console.log(data);
      $('#results').html('<div class="alert alert-dismissible alert-success">' + data.result + '</div>');
    }
  });
   }

</script>
{% endblock %}

BSidesBadgeServer/templates/addalias.html
{% extends "base.html" %} {% block content %}
    
{% load bootstrap %}
{% load staticfiles %}

<h3>Add Alias</h3><hr/>
<div class="alert alert-dismissible alert-info">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Heyo!</strong> Please type in your badge number as well as the alias you wish to associate with it.
</div>

<form action="" method="post" class="">
    {{ form|bootstrap }}
     <div class="actions row">
         <p class="col-md-3 col-sm-5 submit">
             <input type="submit" value="Add Alias" name="_update" class="btn btn-primary" />
         </p>
         
         {% csrf_token %}
     </div>
 </form>



{% endblock %}

BSidesBadgeServer/templates/base.html
{% load staticfiles %}
{% load bootstrap %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>BSides Badge 2016 {% block title %}{% endblock %} </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/simplex.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" media="screen">
    <script src="{% static 'js/jquery-2.2.4.min.js' %}"></script>
    
   
    <style>
      .chosen-container
      {
        min-width: 150px !important;
      }
    </style>
    {% block head %}{% endblock %}
  </head>
  <body >
<div class="container">
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">

      <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-knight"></span> &nbsp;&nbsp;BSides Badge 2016</a> 
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li ><a href="{% url 'dashboard:dashboard' %}">Dashboard</a></li>
        <li ><a href="{% url 'badge:addhash' %}">Challenges </a></li>
        <li ><a href="{% url 'badge:addalias' %}">Alias to Badge</a></li>
        <li ><a href="{% url 'badge:about' %}">About Badges</a></li>
        <li ><a href="{% url 'badge:thegame' %}">The Game</a></li>
        <li ><a href="{% url 'badge:faq' %}">FAQ</a></li>
        
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><a target="_blank" href="http://www.bsidescapetown.co.za/">BSides2016</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  
{% if messages %}
  {% for message in messages %}
    <div  class="alert alert-dismissible alert-{% if message.tags %}{{message.tags}}{% else %}info{% endif %}">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        
            
                {{ message }}
         
       
    </div>
       {% endfor %}
{% endif %}



{% block content %}{% endblock %}


</div>



    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    
</div>
  </body>
</html>

BSidesBadgeServer/templates/challenges.html
{% extends "base.html" %} {% block content %}
    

{% load staticfiles %}
<!--<link rel="stylesheet" href="{% static 'chosen_v1.6.2/chosen.css' %}">--> 
<script src="{% static 'Highcharts/code/highcharts.js' %}"></script>
<script src="{% static 'Highcharts/code/modules/exporting.js' %}"></script>

<h3>Dashboard</h3><hr/>
<div class="alert alert-dismissible alert-info">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Heyo!</strong> This is the current state of <a href="#" class="alert-link">the game</a>.
</div>
<h1>Live Game Stats</h1>
<div class="container" >
<div id="container" style=" width:48%; height: 300px;  float:left;"></div>
<div id="colChart" style=" width:48%; height: 300px; float:right;"></div>
</div>

<h1>Day View</h1>
<div class="container" >
<div id="dayviewcontainer" style=" width:100%; height: 300px;  float:left;"></div>
</div>


<script type="text/javascript">
var currentVals = {'red':0,'green':0,'blue':0}
$(function ()
{
  
  
  $('#dayviewcontainer').highcharts({
        chart: {
            type: 'spline',
			events: {
                    load: function () {
						
                        // set up the updating of the chart each second
						var series = this.series;
						var redseries = this.series[1];
						var greenseries = this.series[2];
						var blueseries = this.series[0];
						var theChart = this;
						
                        setInterval(function () {
						  var currChart = this;
							//$.getJSON({% url 'dashboard:ajax' %},function (data){});
						   $.ajax({
						      url : '{% url 'dashboard:ajax' %}',
						      type: "POST",
						      data : {Type:'fullDay'},
	
						      success: function(data, textStatus, jqXHR)
							   {
								
								  //console.log(data);						
								  redseries.setData(data["red"],false);
								  greenseries.setData(data["green"],false);
								  blueseries.setData(data["blue"],false);
								  theChart.redraw();
								  //series.redraw();
								  
							   }
						   });
							
                            
                        }, 2000);
                    }
                }
        },
        title: {
            text: 'Realtime Team Movement'
        },
        
        
		xAxis: {
            type: 'category',
            
        },
        yAxis: {
            title: {
                text: 'Number of Players'
            },
        },
        tooltip: {
            pointFormat: '<b>{point.y} {series.name} players'
        },
        plotOptions: {
            area: {
                pointStart: 0,
                marker: {
                    enabled: false,
                    symbol: 'square',
                    radius: 2,
                    states: {
                        hover: {
                            enabled: true
                        }
                    }
                }
            }
        },
		//blue,red,green
		colors: ['#7798BF','#DF5353', '#88ff99'],
        series: [
		{
            name: 'Blue',
            data: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        },
		{
            name: 'Red',
           data: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] 
        }, {
            name: 'Green',
           data: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        },
		]
});
  
  
 
  $('#colChart').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: 0,
            plotShadow: false,
			type: 'column',
			events: {
		  	  load: function () {
				
				var currChart = this;
				var series = this.series;
				var redseries = this.series[1];
				var greenseries = this.series[2];
				var blueseries = this.series[0];
		
				setInterval(function () {
				  
				  red = redseries.data[0].y
				  green = greenseries.data[0].y
				  blue = blueseries.data[0].y
				  if (red != currentVals['red'] ||
					  blue != currentVals['blue'] ||
					  green != currentVals['green'])
				  {
					
                    redseries.data[0].y = currentVals['red'];
					
					greenseries.data[0].y = currentVals['green'];
					blueseries.data[0].y = currentVals['blue'];
					series[1].redraw();
					series[2].redraw();
					series[0].redraw();
					
					
                  }
			     }, 1300);
	  }},
        },
        title: {
            text: 'Current Teams'
        },
        tooltip: {
            headerFormat: '',
			pointFormat: '{series.name}: <b>{point.y}</b>'
        },
		
		
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
		colors: ['#7798BF','#DF5353', '#88bb99'],
        series: [
				 {name: 'Blue', data: [80]},
				 {name: 'Red', data: [80]},
				 {name: 'Green', data: [80]}
            
        ],
		
    });
  
  
  
    $('#container').highcharts({
        chart: {
            type: 'area',
			events: {
                    load: function () {

                        // set up the updating of the chart each second
                        var seriesred = this.series[1];
						var seriesgreen = this.series[2];
						var seriesblue = this.series[0];
                        setInterval(function () {
							//$.getJSON({% url 'dashboard:ajax' %},function (data){});
						   $.ajax({
						      url : '{% url 'dashboard:ajax' %}',
						      type: "POST",
						      data : {Type:'statusUpdate',Value:currentVals},
	
						      success: function(data, textStatus, jqXHR)
							   {
								
								var currentdate = new Date(); 
  var datetime = currentdate.getDate() + "/"
				  + (currentdate.getMonth()+1)  + "/" 
				  + currentdate.getFullYear() + " @ "  
				  + currentdate.getHours() + ":"  
				  + currentdate.getMinutes() + ":" 
				  + currentdate.getSeconds();
								if (data["status"] == "update") {
								  currentVals['red'] = data['red'];
								  currentVals['blue'] = data['blue'];
								  currentVals['green'] = data['green'];
								  seriesred.addPoint([datetime,data['red']],true,true);
								  seriesgreen.addPoint([datetime,data['green']],true,true);
								  seriesblue.addPoint([datetime,data['blue']],true,true);
								}
								
							   }
						   });
							
                            
                        }, 1000);
                    }
                }
        },
        title: {
            text: 'Realtime Team Movement'
        },
        
        
		 xAxis: {
		type: 'category'
        },
        yAxis: {
            title: {
                text: 'Number of Players'
            },
        },
        tooltip: {
            pointFormat: '<b>{point.y} {series.name} players'
        },
        plotOptions: {
            area: {
                pointStart: 0,
                marker: {
                    enabled: false,
                    symbol: 'square',
                    radius: 2,
                    states: {
                        hover: {
                            enabled: true
                        }
                    }
                }
            }
        },
		//blue,red,green
		colors: ['#7798BF','#DF5353', '#88ff99'],
        series: [
		{
            name: 'Blue',
            data: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        },
		{
            name: 'Red',
           data: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] 
        }, {
            name: 'Green',
           data: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        },
		]
    });
});

		</script>


{% endblock %}